version: '3.8'

services:
  main:
    image: alpine-vscode
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   target: dev
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ~/.ssh:/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # command: code -a /app serve-web --without-connection-token --accept-server-license-terms --host 0.0.0.0

